### ISSUE TITLE
Default-Route has no method

### ISSUE THREAD

**Issue by kochmarvin** [grafe-team/grafe-framework#27]
**Describe the bug**
When creating a new grafe project the default index route has no method

**To Reproduce**
grafe start [projectName]

**Expected behavior**
Should contain the get method as default

**Desktop (please complete the following information):**
 - Grafe Versions [e.g. 22]
 - Node Version [e.g. 12.x]

**Comment by streimelstefan** [comment]
I already fixed in branch grafe start
