### ISSUE TITLE
.gitignore is beeing replaced by .npmignore when pushed to npm 

### ISSUE THREAD

**Issue by streimelstefan** [grafe-team/grafe-framework#40]
**Describe the bug**
In the starter templates there is a .gitignore file. This file will be changed to a .npmignore by npm upon uploading it.

**To Reproduce**
Latest npm release

1. `grafe start test`
2. suddenly there is a .npmignore file there 

**Expected behavior**
There should be a .gitignore 

**Desktop (please complete the following information):**
 - OS: Windows
 - Grafe CLI: 1.0.0
 - Node Version [e.g. 12.x]

**Additional context**

A possible solution is to add an empty .npmignore like stated in: https://github.com/npm/npm/issues/3763#issuecomment-22255799

**Comment by kochmarvin** [comment]
Possible solution did not work. Renamed '.gitignore' to 'gitignore'. When the new Project gets created the 'createDirectoryContents' checks if the next file is 'gitignore' and renames it to '.gitignore'.
